# Generated by Django 5.2.3 on 2025-06-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auditorName", models.CharField(max_length=20)),
                ("AcademyNum", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Academy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Academyname", models.CharField(max_length=50)),
                ("NumPerson", models.IntegerField(default=0)),
                (
                    "auditorName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="polls.auditor",
                    ),
                ),
            ],
        ),
    ]
