# Generated by Django 5.2.3 on 2025-06-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditor",
            name="Academypassword",
            field=models.IntegerField(default=0),
        ),
    ]
