# Generated by Django 5.2.3 on 2025-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_auditor_academypassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditor",
            name="auditorUnit",
            field=models.CharField(default="null", max_length=50),
        ),
    ]
