# Generated by Django 5.2.3 on 2025-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_auditor_auditorunit"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="responsible1",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="academy",
            name="responsibleTel",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
